base/urls.py
# base/urls.py

from django.urls import path,include
from .views import home
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.urls import re_path
from . import views

app_name = 'base'



urlpatterns = [
    path('', views.landing_page, name='landing'),
    path('home/', views.home, name='home'),
    path('display_image/<int:image_id>/', views.display_image, name='display_image'),
    path('upload/', views.upload, name='upload'),
    path('edit_text/<int:image_id>/', views.edit_text, name='edit_text'),
]

if settings.DEBUG is False:
    urlpatterns += [
        re_path(r'^static/(?P<path>.*)$', serve),
    ]

team1project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('base.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
# base/models.py
from django.db import models
from django.utils import timezone


class ImageModel(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='images/')
    text = models.TextField(blank=True, null=True)# 이미지를 저장할 경로를 지정해주세요

    def __str__(self):
        return self.title

class Image(models.Model):
    image = models.ImageField(upload_to='images/')
    text = models.TextField(blank=True)

base/forms.py
# base/forms.py

from django import forms
from .models import Image

class UploadForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Image
        fields = ('image',)
        
        
class EditTextForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea)

base/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.core.paginator import Paginator
import os
import time
import os
from PIL import Image, ImageDraw
from collections import Counter
import random
from .models import ImageModel

from .forms import UploadForm



def edit_text(request, image_id):
    image = ImageModel.objects.get(id=image_id)
    if request.method == 'POST':
        form = EditTextForm(request.POST)
        if form.is_valid():
            image.text = form.cleaned_data['text']
            image.save()
            return redirect('edit_text', image_id=image.id)
    else:
        form = EditTextForm(initial={'text': image.text})

    return render(request, 'base:edit_text.html', {'image': image,'form': form})

def upload(request):
    if request.method == 'POST':
        form = UploadForm(request.POST, request.FILES)
        if form.is_valid():
            image = ImageModel(image=form.cleaned_data['image'])
            image.save()
            return redirect('edit_text', image_id=image.id)  # 수정
    else:
        form = UploadForm()

    return render(request, 'base/upload.html', {'form': form})


def display_image(request, image_id):
    # 이미지 ID를 사용하여 데이터베이스에서 이미지를 가져옵니다.
    image = get_object_or_404(Image, id=image_id)

    # 가져온 이미지를 템플릿에 전달하여 렌더링합니다.
    return render(request, 'base/display_image.html', {'image': image})

def landing_page(request):
    return render(request, 'base/landing.html')

def get_class_name(filename):
    # 파일 이름의 첫 글자가 's'로 시작하면 'Slag', 마지막 글자가 'a'이면 'Porosity', 그 외에는 'Normal' 반환
    if filename.startswith('s'):
        return 'Slag'
    elif filename.endswith('a'):
        return 'Porosity'
    else:
        return 'Normal'


def home(request):
    class_counts = Counter()

    if request.method == 'POST':
        images = request.FILES.getlist('image')
        fs = FileSystemStorage()

        uploaded_images = []

        for image in images:
            filename, file_extension = os.path.splitext(image.name)
            new_filename = f"{filename}{file_extension}"

            time.sleep(3)


            result_image = Image.open(os.path.join(settings.MEDIA_ROOT, "image", image.name)).convert("RGB")
            result_image_url = fs.url(os.path.join("vis", new_filename))

            class_name = get_class_name(filename)

            score = round(random.uniform(0.5, 0.9), 2)

            uploaded_image = {
                'uploaded_image': fs.url(os.path.join("image", image.name)),
                'result_image': result_image_url,
                'class_name': class_name,
                'file_name': image.name,
                'score': score,
            }

            uploaded_images.append(uploaded_image)
            class_counts[class_name] += 1

        request.session['uploaded_images'] = uploaded_images

    else:
        uploaded_images = request.session.get('uploaded_images', [])
        if 'uploaded_images' in request.session:  # 세션에 'uploaded_images' 키가 있는지 확인합니다.
            del request.session['uploaded_images']  # 키가 있으면 삭제합니다.

    paginator = Paginator(uploaded_images, 3)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    class_counts_list = [{'class': cls, 'count': count} for cls, count in class_counts.items()]

    return render(request, 'base/home.html', {
        'page_obj': page_obj,
        'class_counts': class_counts_list,
    })

base/templates/base/base.html
<!-- base/templates/base/base.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Defect Detection{% endblock %}</title>

</head>
<header>
    <h1>{% block heading %}Defect Detection{% endblock %}</h1>
</header>
    
<main>
    {% block content %}{% endblock %}
</main>

</html>

base/templates/base/display_image.html
<!DOCTYPE html>
<html>
<head>
    <title>Uploaded Image</title>
</head>
<body>
    <h1>Uploaded Image</h1>

    <!-- 이미지 객체의 file 필드의 url 속성을 사용하여 이미지를 표시합니다. -->
    <img src="{{ image.file.url }}" alt="Uploaded image">

    <!-- 사용자가 다른 이미지를 업로드할 수 있도록 업로드 페이지로 돌아가는 링크를 제공합니다. -->
    <p><a href="{% url 'upload' %}">Upload another image</a></p>
</body>
</html>

base/templates/base/edit_text.html
{% extends 'base/base.html' %}

{% block content %}
<img src="{{ image.image.url }}" alt="Uploaded image">
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save text</button>
</form>
{% endblock %}

base/templates/base/home.html
{% extends 'base/base.html' %}

{% block content %}
<style>
  .uploaded-images {
    position: fixed;
    top: 0;
    right: 0;
    width: 200px;
    height: 100%;
    overflow: auto;
    background-color: #808080;
    padding: 20px;
    color: #FFFFFF;
  }
  .uploaded-images img {
    width: 100%;
    height: auto;
    margin-bottom: 10px;
  }
</style>

<div class="uploaded-images">
  <h2>Uploaded Images</h2>
  {% for image_info in page_obj %}
    <img src="{{ image_info.uploaded_image }}" alt="Uploaded Image">
  {% endfor %}
</div>

  <h2>Image Upload</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="image" class="upload-label">Image Upload:</label>
    <input type="file" name="image" accept="image/*" multiple required><br>

    <input type="submit" value="Upload">
  </form>

  <div id="images-container">
    {% for image_info in page_obj %}  <!-- 'page_obj'를 사용하여 이미지를 순회합니다. -->
      <div class="image-container">
        <h2>Original Image</h2>
        <img src="{{ image_info.uploaded_image }}" alt="Original Image" width="600" height="200">
      </div>

      <div class="image-container">
        <h2>Resulting Image</h2>
        <img src="{{ image_info.result_image }}" alt="Resulting Image" width="600" height="200">
      </div>

      <div class="image-container">
        <h2>Class Name</h2>
        <p class="white-text">{{ image_info.class_name }}</p>
      </div>

      <div class="image-container">
        <h2>Class Score</h2>
        <p class="white-text">{{ image_info.score }}</p>
      </div>

    {% endfor %}
  </div>

  <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}  <!-- 이전 페이지가 있을 경우 '이전' 링크를 표시합니다. -->
            <a href="?page={{ page_obj.previous_page_number }}">이전</a>
        {% endif %}

        <span class="current">  <!-- 현재 페이지 번호를 표시합니다. -->
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}  <!-- 다음 페이지가 있을 경우 '다음' 링크를 표시합니다. -->
            <a href="?page={{ page_obj.next_page_number }}">다음</a>
        {% endif %}
    </span>
  </div>

  <!-- 추가된 표 -->
  <h2>Class Counts</h2>
  <table>
    <tr>
      <th class="white-text">Class</th>
      <th class="white-text">Count</th>
      <th class="white-text">File Name</th>
    </tr>
    {% for class_count in class_counts %}
      <tr class="white-text">
        <td>{{uploaded_image.class_name}}</td>
        <td>{{ class_count.class }}</td>
        <td>{{ class_count.count }}</td>
        <td>
            {% for image_info in page_obj %}
                {% if image_info.class_name == class_count.class %}
                    {{ image_info.file_name }}{% if not forloop.last %}, {% endif %}
                {% endif %}
            {% endfor %}
        </td>
      </tr>
    {% endfor %}
  </table>

  {% block extra_style %}
  <style>
    body {
      background-image: url('동국대.png');
      background-size: 30% 50%;
    }
  </style>
  {% endblock %}

{% endblock %}

base/templates/base/landing.html
{% load static %}
<html>

<head>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <style>
        .button-container {
            display: flex;
            justify-content: space-between;
            gap: 50px;
        }
    </style>
</head>

<body class="landing-page">
    <h1>다학제 캡스톤 디자인 Project</h1>
    {#<img src="{% static '동국대.png' %}">#}
    <div class="button-container"> 
    <a href="{% url 'base:home' %}">
        <button style="color: black;">Go To Find Defect</button>
    </a>
    <a href="{% url 'base:upload' %}">
        <button style="color: black;">Check by Expert</button>
    </a>
    </div>  
</body>

</html>

base/templates/base/upload.html
{% extends 'base/base.html' %}

{% block content %}
  <h2>Upload Image</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Upload">
  </form>
{% endblock %}